// Code generated by "stringer -type=PuzzleID"; DO NOT EDIT.

package molekcheatez

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[InvalidPuzzleID-0]
	_ = x[DEPRECATED_Tutorial1-1]
	_ = x[HydrogenPeroxide-2]
	_ = x[DEPRECATED_UnbondingTutorial-3]
	_ = x[NitrousOxide-4]
	_ = x[Ethanol-5]
	_ = x[GHB-6]
	_ = x[Cyanamide-7]
	_ = x[Tranylcypromine-8]
	_ = x[MDMA-9]
	_ = x[Dimercaprol-10]
	_ = x[Nicotine-11]
	_ = x[DEPRECATED_Fentanyl-12]
	_ = x[Ketamine-13]
	_ = x[Propofol-14]
	_ = x[DMT-15]
	_ = x[Caffeine-16]
	_ = x[Mebicar-17]
	_ = x[Phencyclidine-18]
	_ = x[Amphetamine-19]
	_ = x[Barbital-20]
	_ = x[Methylhexanamine-21]
	_ = x[Metformin-22]
	_ = x[Sertraline-23]
	_ = x[Aspirin-24]
	_ = x[Modafinil-25]
	_ = x[Epinephrine-26]
	_ = x[Benzylpiperazine-27]
	_ = x[Pyrazinamide-28]
	_ = x[Lidocaine-29]
	_ = x[DEPRECATED_RCS4-30]
	_ = x[KojicAcid-31]
	_ = x[DMSO-32]
	_ = x[DimethylEther-33]
	_ = x[Piracetam-34]
	_ = x[Chloroform-35]
	_ = x[Valnoctamide-36]
	_ = x[Propranolol-37]
	_ = x[Diazepam-38]
	_ = x[Dapsone-39]
	_ = x[Mescaline-40]
	_ = x[Dimethylthiambutene-41]
	_ = x[SolitaireMain-42]
	_ = x[SwitchToBonus-43]
	_ = x[SwitchToMain-44]
	_ = x[Placeholder-45]
	_ = x[Ibuprofen-46]
	_ = x[LevelEditor-47]
	_ = x[Propylthiouracil-48]
	_ = x[Isoflurane-49]
	_ = x[Inositol-50]
	_ = x[PyridoxalPhosphate-51]
	_ = x[SulfurHexafluoride-52]
	_ = x[Hydrochlorothiazide-53]
	_ = x[Mianserin-54]
	_ = x[Fluorouracil-55]
	_ = x[Cytophosphane-56]
	_ = x[Ethambutol-57]
	_ = x[Nitroglycerin-58]
	_ = x[Fosfomycin-59]
	_ = x[SulfurMustard-60]
	_ = x[Sarin-61]
	_ = x[Paracetamol-62]
	_ = x[ClodronicAcid-63]
	_ = x[Lamotrigine-64]
	_ = x[Methaqualone-65]
	_ = x[Hexestrol-66]
	_ = x[Thiotepa-67]
	_ = x[Mexiletine-68]
	_ = x[Promazine-69]
	_ = x[Altretamine-70]
	_ = x[Pyrimethamine-71]
	_ = x[Lysine-72]
	_ = x[VitaminC-73]
	_ = x[Fluoperazine-74]
	_ = x[Neramexane-75]
	_ = x[ChloralHydrate-76]
	_ = x[Ethchlorvynol-77]
	_ = x[Thalidomide-78]
	_ = x[Bithionol-79]
	_ = x[SolitaireBonus-80]
}

const _PuzzleID_name = "InvalidPuzzleIDDEPRECATED_Tutorial1HydrogenPeroxideDEPRECATED_UnbondingTutorialNitrousOxideEthanolGHBCyanamideTranylcypromineMDMADimercaprolNicotineDEPRECATED_FentanylKetaminePropofolDMTCaffeineMebicarPhencyclidineAmphetamineBarbitalMethylhexanamineMetforminSertralineAspirinModafinilEpinephrineBenzylpiperazinePyrazinamideLidocaineDEPRECATED_RCS4KojicAcidDMSODimethylEtherPiracetamChloroformValnoctamidePropranololDiazepamDapsoneMescalineDimethylthiambuteneSolitaireMainSwitchToBonusSwitchToMainPlaceholderIbuprofenLevelEditorPropylthiouracilIsofluraneInositolPyridoxalPhosphateSulfurHexafluorideHydrochlorothiazideMianserinFluorouracilCytophosphaneEthambutolNitroglycerinFosfomycinSulfurMustardSarinParacetamolClodronicAcidLamotrigineMethaqualoneHexestrolThiotepaMexiletinePromazineAltretaminePyrimethamineLysineVitaminCFluoperazineNeramexaneChloralHydrateEthchlorvynolThalidomideBithionolSolitaireBonus"

var _PuzzleID_index = [...]uint16{0, 15, 35, 51, 79, 91, 98, 101, 110, 125, 129, 140, 148, 167, 175, 183, 186, 194, 201, 214, 225, 233, 249, 258, 268, 275, 284, 295, 311, 323, 332, 347, 356, 360, 373, 382, 392, 404, 415, 423, 430, 439, 458, 471, 484, 496, 507, 516, 527, 543, 553, 561, 579, 597, 616, 625, 637, 650, 660, 673, 683, 696, 701, 712, 725, 736, 748, 757, 765, 775, 784, 795, 808, 814, 822, 834, 844, 858, 871, 882, 891, 905}

func (i PuzzleID) String() string {
	if i < 0 || i >= PuzzleID(len(_PuzzleID_index)-1) {
		return "PuzzleID(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _PuzzleID_name[_PuzzleID_index[i]:_PuzzleID_index[i+1]]
}
